[workspace]
authors = ["Henry Dawson <hdd29@cornell.edu>"]
channels = ["conda-forge"]
name = "theRefseqening"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.5,<3.14"
tqdm = ">=4.67.1,<5"
ipykernel = ">=7.1.0,<8"
r-irkernel = ">=1.3.2,<2"
jupyterlab = ">=4.4.10,<5"
pixi-kernel = ">=0.6.7,<0.7"
pandarallel = ">=1.6.5,<2"
r-xml2 = ">=1.3.8,<2"
"r-data.table" = ">=1.17.8,<2"
r-units = ">=0.8_7,<0.9"
r-terra = ">=1.8_42,<2"
r-oai = ">=0.4.0,<0.5"
r-sf = ">=1.0_20,<2"
r-rgbif = ">=3.8.2,<4"
r-rnaturalearth = ">=1.0.1,<2"
r-bien = ">=1.2.7,<2"
r-ncdf4 = ">=1.24,<2"
r-plyr = ">=1.8.9,<2"
r-reshape2 = ">=1.4.4,<2"
r-tidyverse = ">=2.0.0,<3"
libgdal-netcdf = ">=3.10.2,<4"
r-matrix = ">=1.7_3,<2"
fastparquet = ">=2024.11.0,<2025"
r-geosphere = ">=1.5_20,<2"
r-arrow = ">=19.0.1,<20"
r-optparse = ">=1.7.5,<2"
r-bglr = ">=1.1.4,<2"
r-pheatmap = ">=1.0.13,<2"
r-lme4 = ">=1.1_37,<2"
r-biocmanager = ">=1.30.26,<2"
r-phylosignal = ">=1.3.1,<2"
r-ape = ">=5.8_1,<6"
r-geiger = ">=2.0.11,<3"
r-caper = ">=1.0.4,<2"
r-adephylo = ">=1.1_17,<2"
r-phylobase = ">=0.8.12,<0.9"
r-nlme = ">=3.1_168,<4"
r-proc = ">=1.19.0.1,<2"
r-glmnet = ">=4.1_10,<5"
r-peptides = ">=2.4.6,<3"
r-lsd = ">=4.1_0,<5"
git-filter-repo = ">=2.38.0,<3"
r-domc = ">=1.3.8,<2"
rpds-py = ">=0.28.0,<0.29"
r-zoo = ">=1.8_14,<2"

[pypi-dependencies]
biopython = ">=1.85, <2"
numpy = ">=2.3.1, <3"
pandas = ">=2.3.1, <3"
tqdm = ">=4.67.1, <5"
scikit-learn = ">=1.7.0, <2"
matplotlib = ">=3.10.3, <4"
seaborn = ">=0.13.2, <0.14"
aaindex = ">=1.1.2, <2"
pybiolib = ">=1.2.1308, <2"
