_wandb:
    value:
        cli_version: 0.23.1
        e:
            s2frv8w8t6j247jfxausa6i5c7m7zlq2:
                codePath: src/util_raxWatcher.py
                codePathLocal: src/util_raxWatcher.py
                cpu_count: 44
                cpu_count_logical: 88
                disk:
                    /:
                        total: "321965260800"
                        used: "49087815680"
                email: hdd29@cornell.edu
                executable: /local/workdir/hdd29/chloroplast_genome_evaluation/.pixi/envs/default/bin/python
                git:
                    commit: 7c3836cdeddd754dfca971b3ba644568ac050441
                    remote: git@github.com:hddawson/chloroplast_genome_evaluation.git
                host: cbsulm24.biohpc.cornell.edu
                memory:
                    total: "540127846400"
                os: Linux-5.19.17-x86_64-with-glibc2.34
                program: /local/workdir/hdd29/chloroplast_genome_evaluation/src/util_raxWatcher.py
                python: CPython 3.13.9
                root: /local/workdir/hdd29/chloroplast_genome_evaluation
                startedAt: "2025-12-17T20:17:14.157908Z"
                writerId: s2frv8w8t6j247jfxausa6i5c7m7zlq2
        m: []
        python_version: 3.13.9
        t:
            "3":
                - 3
                - 13
            "4": 3.13.9
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
